### PR TITLE
Remove kube-rbac-proxy

### LINKED ISSUE #502: :warning: Action Required: Replace Deprecated gcr.io/kubebuilder/kube-rbac-proxy
## Description

:warning: **The image `gcr.io/kubebuilder/kube-rbac-proxy` is deprecated and will become unavailable.**
**You must move as soon as possible, sometime from early 2025, the GCR will go away.**

> _Unfortunately, we're unable to provide any guarantees regarding timelines or potential extensions at this time. Images provided under GRC will be unavailable from March 18, 2025, [as per announcement](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr). However, `gcr.io/kubebuilder/`may be unavailable before this date due [to efforts to deprecate infrastructure](https://github.com/kubernetes/k8s.io/issues/2647)._

- **If your project uses `gcr.io/kubebuilder/kube-rbac-proxy`, it will be affected.**
  Your project may fail to work if the image cannot be pulled. **You must take action as soon as possible.**

- However, if your project is **no longer using this image**, **no action is required**, and you can close this issue.

## Using the image `gcr.io/kubebuilder/kube-rbac-proxy`?

[kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) was historically used to protect the metrics endpoint. However, its usage has been discontinued in [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder). The default scaffold now leverages the [`WithAuthenticationAndAuthorization`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization) feature provided by [Controller-Runtime](https://github.com/kubernetes-sigs/controller-runtime).

This feature provides integrated support for securing metrics endpoints by embedding authentication (`authn`) and authorization (`authz`) mechanisms directly into the controller manager's metrics server, replacing the need for (https://github.com/brancz/kube-rbac-proxy) to secure metrics endpoints.

### What To Do?

**You must replace the deprecated image `gcr.io/kubebuilder/kube-rbac-proxy` with an alternative approach. For example:**
- Update your project to use [`WithAuthenticationAndAuthorization`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization):
  > _You can fully upgrade your project to use the latest scaffolds provided by the tool or manually make the necessary changes. Refer to the [FAQ and Discussion](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907) for detailed instructions on how to manually update your project and test the changes._
- Alternatively, replace the image with another trusted source at your own risk, as its usage has been discontinued in Kubebuilder.

**For further information, suggestions, and guidance:**
- 📖 [FAQ and Discussion](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907)
- 💬 Join the Slack channel: [#kubebuilder](https://communityinviter.com/apps/kubernetes/community#kubebuilder).

> **NOTE:** _This issue was opened automatically as part of our efforts to identify projects that might be affected and to raise awareness about this change within the community. If your project is no longer using this image, **feel free to close this issue**._

We sincerely apologize for any inconvenience this may cause.

**Thank you for your cooperation and understanding!** :pray:

### PR DESCRIPTION
**Pull request by dgn**
Replaces proxy with controller-runtime functionality. Fixes #502.

### CODE REVIEW

**Comment by FilipB** [comment]
@dgn could you please confirm that [following](https://gitlab.cee.redhat.com/istio/cpaas/containers-midstream/-/blob/rhossm-3.0-rhel-9/distgit/containers/openshift-istio-operator-prod-operator-metadata/render_templates?ref_type=heads#L41) can be removed after this?

**Comment by dgn** [comment]
> @dgn could you please confirm that [following](https://gitlab.cee.redhat.com/istio/cpaas/containers-midstream/-/blob/rhossm-3.0-rhel-9/distgit/containers/openshift-istio-operator-prod-operator-metadata/render_templates?ref_type=heads#L41) can be removed after this?

Yep!

File: tests/e2e/operator/operator_install_test.go [hunk 1]
```diff
@@ -90,7 +95,83 @@ var _ = Describe("Operator", Ordered, func() {
...
+metadata:
+  name: metrics-reader-rolebinding
+roleRef:
+  apiGroup: rbac.authorization.k8s.io
+  kind: ClusterRole
+  name: %s
+subjects:
+- kind: ServiceAccount
+  name: %s
+  namespace: %s
```
Comment (sridhargaddam) [inline tests/e2e/operator/operator_install_test.go:118]: Nice work Daniel. I verified the PR in both v4 and dualStack clusters and it works fine.

```
$ curl -4 -s -k -H "Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`" https://sail-operator-metrics-service.sail-operator.svc.cluster.local:8443/metrics
# HELP certwatcher_read_certificate_errors_total Total number of certificate read errors
# TYPE certwatcher_read_certificate_errors_total counter
certwatcher_read_certificate_errors_total 0
# HELP certwatcher_read_certificate_total Total number of certificate reads
# TYPE certwatcher_read_certificate_total counter
certwatcher_read_certificate_total 0
```

```
$ curl -6 -s -k -H "Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`" https://sail-operator-metrics-service.sail-operator.svc.cluster.local:8443/metrics
# HELP certwatcher_read_certificate_errors_total Total number of certificate read errors
# TYPE certwatcher_read_certificate_errors_total counter
certwatcher_read_certificate_errors_total 0
# HELP certwatcher_read_certificate_total Total number of certificate reads
# TYPE certwatcher_read_certificate_total counter
certwatcher_read_certificate_total 0
```

Suggestion:

1. Instead of spawning the "curl-metrics" pod in the "sail-operator" namespace, probably it would be good to create a new namespace and run the curl from that namespace.

2. In the current state after running the e2e test, the `curl-metrics` pod continues to stay in "completed" state. If we use a different namespace, we can even delete the namespace after the validation (i.e., in Line 178) to remove all the test artifacts.

Comment (dgn) [reply tests/e2e/operator/operator_install_test.go:118]: Thanks Sridhar! Good idea to use a different namespace. Will push a change

**Review by sridhargaddam — APPROVED** [review]
