### PR TITLE
Remove `--default-profile` in favor of automatic platform detection

### LINKED ISSUE #351: [BUG] OperatorHub.io deployment should not default to the "openshift" profile
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Bug Description

Install the Sail operator from OperatorHub.io.

Now look at the operator's arguments and look at the default profile:

```
$ kubectl get deployment -n operators sail-operator -ojsonpath={..containers[1].args} | jq
[
  "--health-probe-bind-address=:8081",
  "--metrics-bind-address=127.0.0.1:8080",
  "--default-profile=openshift"
]
```

Notice [the CSV defines](https://github.com/istio-ecosystem/sail-operator/blob/0.1.0/bundle/manifests/sailoperator.clusterserviceversion.yaml#L648) the default-profile as "openshift". Since 99% of the time, users of the OperatorHub.io operator will not be on OpenShift, the default profile should be different.

It should be one of these (`default` is probably the best choice): https://istio.io/latest/docs/setup/additional-setup/config-profiles/

### Operator Version

0.1.0

### Link to Gist with Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by luksa**
Fixes #351 

When the operator detects that it's running on OpenShift, it sets the default profile to "openshift".

### CODE REVIEW

File: cmd/main.go [hunk 1]
```diff
@@ -126,6 +124,19 @@ func main() {
 
 	chartManager := helm.NewChartManager(mgr.GetConfig(), os.Getenv("HELM_DRIVER"))
 
+	platform, err := config.DetectPlatform(mgr.GetConfig())
+	if err != nil {
+		setupLog.Error(err, "unable to detect platform")
```
Comment (sridhargaddam) [inline cmd/main.go:129]: This is failing on Kind clusters.

```
sail-operator 2024-10-17T16:56:45Z    INFO    setup    version.BuildInfo{Version:"0.2.0", GitRevision:"bfe3fa673529023e9d1035ec87740c167d230fbd", BuildStatus:"Modified", GitTag:"unknown", GoVersion:"go1.23.2", GoArch:"linux/amd64", ControllerRuntime:"v0.19.0"}
sail-operator 2024-10-17T16:56:45Z    INFO    setup    reading config
sail-operator 2024-10-17T16:56:45Z    INFO    setup    config loaded    {"config": {"ImageDigests":{}}}
sail-operator 2024-10-17T16:56:45Z    ERROR    setup    unable to detect platform    {"error": "the server could not find the requested resource"}
sail-operator main.main
sail-operator     ./main.go:129
sail-operator runtime.main
sail-operator     runtime/proc.go:272
```

Comment (luksa) [reply cmd/main.go:129]: Thanks! Fixed. (I think)

**Review by sridhargaddam — APPROVED** [review]
